### ISSUE TITLE
RHEL >=8 clones?

### ISSUE THREAD

**Issue by lrvl** [nilfs-dev/nilfs2-kmod7#1]
Would this work with RHEL 8 or higher (AlmaLinux/Rocky)?

**Comment by konis** [comment]
I pushed out nilfs2-kmod8 for RHEL 8 clones and am trying to make nilfs2-kmod9 for RHEL 9 clones (not yet published).  nilfs2-kmod8 works at least for the recent version of AlmaLinux 8 , Rocky 8 and CentOS Stream 8.   For past 8.x versions, a little more work is required.

Please try them for  RHEL 8 and higher.  nilfs2-kmod7 will fail due to many build errors.
It's hard to maintain the standalone module in a single tree because RHEL backports many changes from new kernels for each minor version  and needs code switching with crafty ifdef macros.

Thank you.

**Comment by konis** [comment]
I just released nilfs2-kmod9 for RHEL 9 clones which is customized and tested for AlmaLinux 8, Rocky Linux 8, and CentOS Stream 9.
Will close this issue.
